### ISSUE TITLE
Escrever sobre assistente virtual

### ISSUE THREAD

**Issue by NathanReis** [NathanReis/FTT-TCC#20]
### O que fazer

Buscar referências confiáveis relacionadas a assistente virtual e adicionar um sub tópico no artigo científico na parte de assistente virtual.

Deverá ter um subtítulo para Assistente Virtual em relação ao referencial teórico.

Exemplo:

- Referencial teórico
  - Assistente virtual

### Motivo

Por ser uma tecnologia que estará presente na solução, deve ser falado sobre ela.

### Atividades

- [x] Buscar referências sobre assistente virtual
(CRUZ; ALENCAR; SCHMITZ, 2013); https://developer.amazon.com/pt-BR/alexa
- [x] Extrair informações sobre conceito, definição, funcionamento, vantagens, desvantagens, etc...
- [x] Escrever a seção da assistente virtual

**Comment by OliveiraWilliam** [comment]
Faltou vantagens/desvantagens
