### ISSUE TITLE
Criar crud de supermercados

### ISSUE THREAD

**Issue by vitor-lupinetti** [NathanReis/FTT-TCC#43]
### O que fazer
Criar migration para criação da tabela de supermercados, para que seja possível salvar os mercados em que foram realizadas as compras para poder comparar preços de produtos entre mercados.

### Atividades

- [ ] Criar migration para criação da tabela
- [ ] Criar controller de supermercados
- [ ] Criar service de supermercados
- [ ] Criar rotas para supermercados

**Comment by NathanReis** [comment]
Removida pois não se encaixa mais no escopo do projeto.
