### ISSUE TITLE
Realizar análises úteis para mercados

### ISSUE THREAD

**Issue by vitor-lupinetti** [NathanReis/FTT-TCC#46]
### O que fazer
Realizar análise nos dados que sejam úteis para mercados, visando futuras parceiras e geração de receitas

### Atividades

- [ ] Analisar produtos mais consumidos por cliente/ grupo de usuários
- [ ] Analisar produtos mais consumidos por região
- [ ] Analisar produtos mais consumidos por época
- [ ] Analisar quais produtos mais são comprados novamente por um mesmo cliente, e quais são menos comprados por um mesmo cliente
- [ ] Analisar quais produtos são mais vendidos pelo mercado em comparação a mercados concorrentes
- [ ] Analisar quais produtos são menos vendidos pelo mercado em comparação a mercados concorrentes

**Comment by NathanReis** [comment]
Removida pois não se encaixa mais no escopo do projeto.
